/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividade;

import java.util.Random;

/**
 *
 * @author rsouza
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    int jogador, computador;

    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        BtPedra = new javax.swing.JButton();
        BtPapel = new javax.swing.JButton();
        BtTesoura = new javax.swing.JButton();
        Jogador = new java.awt.Label();
        maquina = new java.awt.Label();
        BtJogar = new javax.swing.JButton();
        resultText = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Jogador 1:");

        label2.setText("Jogador 2:");

        BtPedra.setText("Pedra");
        BtPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPedraActionPerformed(evt);
            }
        });

        BtPapel.setText("Papel");
        BtPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPapelActionPerformed(evt);
            }
        });

        BtTesoura.setText("Tesoura");
        BtTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTesouraActionPerformed(evt);
            }
        });

        Jogador.setText("zero");

        maquina.setText("zero");

        BtJogar.setText("JOGAR");
        BtJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtJogarActionPerformed(evt);
            }
        });

        resultText.setText("label3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtPedra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtPapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtTesoura))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtJogar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(maquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Jogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtPedra)
                    .addComponent(BtPapel)
                    .addComponent(BtTesoura))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(BtJogar)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPedraActionPerformed
        // TODO add your handling code here
        String resultado = (BtPedra.getText());
        Jogador.setText(resultado);
    }//GEN-LAST:event_BtPedraActionPerformed

    private void BtJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtJogarActionPerformed
        // TODO add your handling code here:
        Random rnd = new Random();
        int computador;

        computador = rnd.nextInt(1, 4);
        switch (computador) {
            case 1:
                String resultado = (BtPedra.getText());
                maquina.setText(resultado);
                break;
            case 2:
                resultado = (BtPapel.getText());
                maquina.setText(resultado);
                break;
            case 3:
                resultado = (BtTesoura.getText());
                maquina.setText(resultado);
                break;

    }//GEN-LAST:event_BtJogarActionPerformed
       
        switch (Jogador.getText()) {
            case "Pedra":
               switch (computador) {
                    case 1:
                        resultText.setText("Empate");
                        break;
                    case 2:
                        resultText.setText("Perdeu");
                        break;
                    case 3:
                        resultText.setText("Ganhou");
                        break;
                }
               break;
            case "Papel":
                switch (computador) {
                    case 1:
                        resultText.setText("Ganhou");
                        break;
                    case 2:
                        resultText.setText("Empate");
                        break;
                    case 3:
                        resultText.setText("Perdeu");
                        break;
                }
                break;
                
            case "Tesoura":
                switch (computador) {
                    case 1:
                        resultText.setText("Perdeu");
                        break;
                    case 2:
                        resultText.setText("Ganhou");
                        break;
                    case 3:
                        resultText.setText("Empate");
                        break;
                }
               
        }

    }

    private void BtPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPapelActionPerformed
        // TODO add your handling code here:
        String resultado = (BtPapel.getText());
        Jogador.setText(resultado);

    }//GEN-LAST:event_BtPapelActionPerformed

    private void BtTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTesouraActionPerformed
        // TODO add your handling code here:
        String resultado = (BtTesoura.getText());
        Jogador.setText(resultado);
    }//GEN-LAST:event_BtTesouraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtJogar;
    private javax.swing.JButton BtPapel;
    private javax.swing.JButton BtPedra;
    private javax.swing.JButton BtTesoura;
    private java.awt.Label Jogador;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label maquina;
    private java.awt.Label resultText;
    // End of variables declaration//GEN-END:variables
}
